name: "Maintenance Mode"

on:
  workflow_dispatch:
    inputs:
      maintenance_site:
        required: true
        type: string
      maintenance_mode:
        required: true
        type: boolean
      domain:
        type: choice
        description: domain
        options:
        - s3licensing.net
        - s3licensing.com
        - s3gov.com

jobs:
    maintenance:
        runs-on: ubuntu-latest
        env:
          run: ${{ github.event.inputs.maintenance_mode }}
          site : ${{ github.event.inputs.maintenance_site }}
          domain: ${{ github.event.inputs.domain }}
        steps:
          - name: checkout code
            uses: actions/checkout@v4

          - name: Maintenance Mode Off
            if: ${{ env.run == 'false' }}
            run: |
              python3 maint.py -e ${{ env.site }} -d ${{ env.domain }}
              cat stuff/workers.tf

          - name: Maintenance Mode On
            if: ${{ env.run == 'true' }}
            run: |
              python3 maint.py -e ${{ env.site }} -d ${{ env.domain }} -m
              cat stuff/workers.tf

          - name: Commit and push
            run: |
              git config user.name 'github-actions'
              git config user.email 'actions@github.com'
              git status | grep -i "working tree clean" && exit 0
              branch=$(date +%Y%m%d%H%M%S)_${{env.site }}_mm_${{ env.run }}
              git checkout -b $branch
              git add . && git commit -m "maintenance for ${{ env.site }} ${{ env.run }}" && git push origin $branch
              gh pr create --base master --head $branch --title "maintenance ${{ env.run }} for ${{ env.site }}" --body ""
