name: "Maintenance Mode"

on:
  workflow_dispatch:
    inputs:
      maintenance_site:
        required: true
        type: string
      maintenance_mode:
        required: true
        type: boolean

jobs:
    maintenance:
        runs-on: ubuntu-latest
        env:
          run: ${{ github.event.inputs.maintenance_mode }}
          site : ${{ github.event.inputs.maintenance_site }}
          file_path: "stuff/workers.tf"
        steps:
          - name: checkout code
            uses: actions/checkout@v4

          - name: Maintenance Mode Off
            if: ${{ env.run == 'false' }}
            run: |
              sed -i ${{ env.file_path }} -e 'd/${{ env.site }}'

          - name: Maintenance Mode On
            if: ${{ env.run == 'true' }}
            shell: python
            run: |
              f=open("${{env.file_path}}", "w")
              lines=f.readlines()
              patterns_index=lines.index("  patterns = [\n")
              site_add="   \"${{env.site}}.s3licensing.net/*\",\n"
              lines.insert(patterns_index+1,site_add)
              newtext=''.join(lines)
              f.write(newtext)
              f.close()

          - name: Commit and push
            run: |
              git config user.name 'github-actions'
              git config user.email 'actions@github.com'
              git status || grep -i "working tree clean" || git commit -am "maintenance for ${{ env.site }} ${{ env.run }}" && git push
