---
name: "Maintenance Mode"
on:
  workflow_dispatch:
    inputs:
      site_input:
        description: input a custom site
        type: string
      site_choice:
        description: choose a site
        type: choice
        options:
          - none
          - multitenant-prod
          - ar-prod
          - ebci-prod
          - la-prod
          - mn-prod
          - mo-prod
          - oh-prod
          - or-prod
          - maintenance-prod
      maintenance_mode:
        required: true
        type: boolean

jobs:
  maintenance:
    runs-on: ubuntu-latest
    env:
      run: ${{ github.event.inputs.maintenance_mode }}
      choice: ${{ github.event.inputs.site_choice }}
      custom: ${{ github.event.inputs.site_input }}
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: dependency installation
        run: |
          command -v gh || ( sudo apt update && sudo apt install gh -y )

      - name: Maintenance Mode - site from list
        if: ${{ env.custom == '' }}
        run: |
          python3 scripts/maint.py -e ${{ env.choice }} -m ${{ env.run }} -c

      - name: Maintenance Mode - custom input
        if: ${{ env.choice == 'none' }}
        run: |
          python3 scripts/maint.py -e ${{ env.custom }} -m ${{ env.run }} -c
