name: "Maintenance Mode"

on:
  workflow_dispatch:
    inputs:
      maintenance_site:
        required: true
        type: string
      maintenance_mode_enabled:
        required: true
        type: boolean

jobs:
    maintenance:
        runs-on: ubuntu-latest
        env:
          run: ${{ github.event.inputs.maintenance_mode_enabled }}
          site : ${{ github.event.inputs.maintenance_site }}
        steps:
          - name: checkout code
            uses: actions/checkout@v4
          - name: Show var
            run: |
              echo "run: ${{ env.run }}"
              echo "site: ${{ env.site }}"
          - name: disable maintenance mode
            if: ${{ env.run }} == "false"
            run: |
              echo "Disable Maintenance"
          - name: enable maintenance mode
            if: ${{ env.run }} == "true"
            run: |
              echo "Enable Maintenance"
