name: "Maintenance Mode"

on:
  workflow_dispatch:
    inputs:
      maintenance_site:
        required: true
        type: string
      maintenance_mode_enabled:
        required: true
        type: boolean

jobs:
    maintenance:
        runs-on: ubuntu-latest
        env:
          run: ${{ github.event.inputs.maintenance_mode_enabled }}
          site : ${{ github.event.inputs.maintenance_site }}
        steps:
          - name: checkout code
            uses: actions/checkout@v4
          - name: Show var
            run: |
              echo "run: ${{ env.run }}"
              echo "site: ${{ env.site }}"
          - name: set maintenance mode
            run: |
              if [[ ${{ env.run }} == "true" ]];then
                echo "Enable Maintenance"
              else
                echo "Disable Maintenance"
              fi
