name: Rebase Pull Request

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  main:
    name: Rebase
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.ELEVATED_TOKEN }}

      - name: Rebase
        run: |
          git rebase main
          git push origin ${{ github.ref }}

      - name: automatic rebase
        uses: cirrus-actions/rebase@1.5
        env:
          GITHUB_TOKEN: ${{ secrets.ELEVATED_TOKEN }}

