name: Rebase Pull Request

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
env:
  DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}

jobs:
  main:
    name: Rebase
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: perform merge
        run: |
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config --global user.name "${GITHUB_ACTOR}"
          git fetch
          git checkout "$DEFAULT_BRANCH"
          git checkout "$GITHUB_HEAD_REF"
          git rebase "$DEFAULT_BRANCH"
          git push -f

