name: Merge Schedule

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
  schedule:
    - cron: '*/10 * * * *'

env:
  DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}

jobs:
  merge_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: rebase on default branch and force push
        run: |
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config --global user.name "${GITHUB_ACTOR}"
          git fetch
          git checkout "$DEFAULT_BRANCH"
          git checkout "$GITHUB_HEAD_REF"
          git rebase "$DEFAULT_BRANCH"
          git push -f

      - uses: gr2m/merge-schedule-action@v2
        with:
          # Merge method to use. Possible values are merge, squash or
          # rebase. Default is merge.
          merge_method: rebase
          # Time zone to use. Default is UTC.
          time_zone: 'US/Central'
          # Require all pull request statuses to be successful before
          # merging. Default is `false`.
          require_statuses_success: 'true'
          # Label to apply to the pull request if the merge fails. Default is
          # `automerge-fail`.
          automerge_fail_label: 'merge-schedule-failed'
        env:
          GITHUB_TOKEN: ${{ secrets.ELEVATED_TOKEN }}
